spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shiro-plus?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        # 初始化时建立物理连接连接的个数
        initialSize: 5
        # 最小连接池数量
        minIdle: 5
        # 最大连接池数量
        maxActive: 20
        # 获取连接时最大等待时间(ms)，即60s
        maxWait: 60000
        # 1.Destroy线程会检测连接的间隔时间；2.testWhileIdle的判断依据
        timeBetweenEvictionRunsMillis: 60000
        # 最小生存时间ms
        minEvictableIdleTimeMillis: 300000
        # 用来检测连接是否有效的sql
        validationQuery: SELECT 1 FROM DUAL
        # 申请连接时执行validationQuery检测连接是否有效，启用会降低性能
        testOnBorrow: false
        # 归还连接时执行validationQuery检测连接是否有效，启用会降低性能
        testOnReturn: false
        # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，
        # 执行validationQuery检测连接是否有效，不会降低性能
        testWhileIdle: true
        # 是否缓存preparedStatement，mysql建议关闭
        poolPreparedStatements: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 关闭缓存，模板热部署
        # cache: false
    redis:
      host: 127.0.0.1
      port: 6379
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      cache: false
      encoding: UTF-8
    devtools:
      restart:
        #热更新开关
        enabled: true
        #指定热更新目录
        additional-paths: src/main
        #指定不更新目录
        additional-exclude: test
#配置登录页面,此处可以省略(省略则使用登录系统默认页面)
teaching:
  browser:
    loginPage: /web-login.html
    loginResponseType: REDIRECT
mybatis:
    mapper-locations: classpath:mappers/*.xml
    configuration:
      map-underscore-to-camel-case: true